composer.json, composer.lock
I couldn't get #84 to work without requiring `drupal/config_filter`
=> fix: add config_filter to composer

.gitattributes, composer.lock, composer.patches.json
Refs: OPS-8943
XSS filtering patch didn't apply - the updated patch is slightly different but looks close to being accepted
=> chore: manual periodic update as it failed on applying a patch

html/modules/custom/hr_paragraphs/hr_paragraphs.routing.yml, html/modules/custom/hr_paragraphs/hr_paragraphs.services.yml, html/modules/custom/hr_paragraphs/src/Controller/BaseKeyFiguresController.php, html/modules/custom/hr_paragraphs/src/Controller/WebhookController.php
=> feat: Listen for changes and clear cache

config/core.entity_form_display.paragraph.featured_number.default.yml, config/core.entity_form_display.paragraph.featured_numbers.default.yml, config/core.entity_view_display.paragraph.featured_number.default.yml, config/core.entity_view_display.paragraph.featured_numbers.default.yml, config/field.field.group.cluster.field_paragraphs.yml, config/field.field.group.operation.field_paragraphs.yml, config/field.field.node.landing_page.field_paragraphs.yml, config/field.field.node.page.field_paragraphs.yml, config/field.field.paragraph.featured_number.field_country.yml, config/field.field.paragraph.featured_number.field_figures.yml, config/field.field.paragraph.featured_number.field_show_sparklines.yml, config/field.field.paragraph.featured_number.field_source.yml, config/field.field.paragraph.featured_number.field_year.yml, config/field.field.paragraph.featured_numbers.field_numbers.yml, config/field.field.paragraph.featured_numbers.field_text.yml, config/field.field.paragraph.featured_numbers.field_title.yml, config/field.storage.paragraph.field_numbers.yml, config/field.storage.paragraph.field_source.yml, config/paragraphs.paragraphs_type.featured_number.yml, config/paragraphs.paragraphs_type.featured_numbers.yml, html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/src/Controller/BaseKeyFiguresController.php, html/modules/custom/hr_paragraphs/src/Controller/FtsKeyFiguresController.php, html/modules/custom/hr_paragraphs/src/Controller/InformKeyFiguresController.php, html/themes/custom/hri_admin/js/keyfigures.js, phpcs.xml
=> feat: Inform risk

html/modules/custom/hr_paragraphs/src/Controller/BaseKeyFiguresController.php
=> feat: Use updated for date if present

.dockerignore, docker/Dockerfile
=> chore: add dockerignore and update dockerfile

html/modules/custom/hr_mailchimp/hr_mailchimp.module, html/modules/custom/hr_mailchimp/src/Form/HrMailchimpAlertForm.php
=> feat: mail confirm

html/modules/custom/hr_paragraphs/src/Controller/BaseKeyFiguresController.php, html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-key-figures.html.twig, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-key-figures.html.twig
=> feat: allow string data

.github/workflows/composer-update.yml
=> chore: Use PHP8.1

html/themes/custom/common_design_subtheme/css/styles.css
=> [NUM-25] subscribe with CSS cols

composer.json, composer.lock, config/config_split.config_split.config_dev.yml, config/core.extension.yml, config/environment_indicator.settings.yml, config/environment_indicator.switcher.dev.yml, config/environment_indicator.switcher.local.yml, config/environment_indicator.switcher.prod.yml, config_dev/environment_indicator.indicator.yml
=> chore: add and configure environment_indicator

composer.lock, composer.patches.json
GHA failed on patch, https://github.com/UN-OCHA/numbers-site/actions/runs/4879792002/jobs/8706703063
=> chore: Composer update

composer.lock, html/themes/custom/common_design_subtheme/components/ocha-key-figures/ocha-key-figures.css, html/themes/custom/common_design_subtheme/templates/ocha-key-figures-extended-figure--top-donors.html.twig, html/themes/custom/common_design_subtheme/templates/ocha-key-figures-extended-figure--top-sectors.html.twig
=> feat: Styling top donors and sectors

html/themes/custom/common_design_subtheme/components/ocha-key-figures/ocha-key-figures.css
=> fix: scope table styles to actual table cells

.github/workflows/composer-update.yml, .github/workflows/docker-build-image.yml, .github/workflows/run-tests.yml
=> chore: Bypass stupid dependabot.

html/themes/custom/common_design_subtheme/components/ocha-key-figures/ocha-key-figures.css, html/themes/custom/common_design_subtheme/js/login_destination.js, html/themes/custom/common_design_subtheme/js/service-worker-registration.js, html/themes/custom/common_design_subtheme/package-lock.json
=> chore: run npm fix

config/config_split.config_split.config_dev.yml
=> fix: Properly ensure devel module does not get enabled by config_split on dev.

composer.lock
=> chore: Fix accesscheck

composer.json
Should resolve conflict in https://github.com/UN-OCHA/numbers-site/pull/212
=> Resolve merge conflict

composer.lock
=> Drupal core - Critical - Cache poisoning - SA-CORE-2023-006
